### ISSUE TITLE
danke

### ISSUE THREAD

**Issue by jeremywrnr** [jeremywrnr/testing#43]
[issue screenshot](http://codepilot.meteor.com/screenshot/inRZ4W9C6ccoyhSbv)
[live code here](http://codepilot.meteor.com/render/HEczdanWiqvGiFS2P)
html:
```html
<head>
  <title>my website</title>
</head>

<body>
  <h1>welcome!</h1>
  <p>you can edit this code - please do!</p>
  <h2>here is kitty</h2>
  <img id="kitty" src="http://placekitten.com/202/200"/>
</body>
```
css:
```css
body {
    font-family: Arial, sans-serif;
    padding: 10px;
    margin: 10px;
}

h1 {
    font-size: 3em; 
}

h2 {
    font-size: 1.5em; 
}
```
js:
```js
// rejoice - jquery is enabled!

console.log("Hello branched world");

$("#kitty").click(function() {
   console.log("you clicked on the kitty. thank you!") 
});
```
