### ISSUE TITLE
very sciencey cat

### ISSUE THREAD

**Issue by codepilot-test** [jeremywrnr/testing#46]
[issue screenshot](http://codepilot.meteor.com/screenshot/PJ2A8CwhdGGsHJW68)
[live code here](http://codepilot.meteor.com/render/W4zZjL4DSPTbZiQ9k)
html:
```html
<head>
  <title>my website</title>
</head>

<body>
  <h1>welcome!</h1>
  <p>you can edit this code - please do!</p>
  <h2>here is kitty</h2>
  <img id="kitty" src="http://erinhunter.katecary.co.uk/wp-content/uploads/2014/12/science-cat.jpg"/>
</body>
```
css:
```css
body {
    font-family: Arial, sans-serif;
    padding: 10px;
    margin: 10px;
}

h1 {
    font-size: 3em; 
}

h2 {
    font-size: 1.5em; 
}

img {
    width: 100%; 
}
```
js:
```js
// rejoice - jquery is enabled!

console.log("Hello branched world");

$("#kitty").click(function() {
   console.log("you clicked on the kitty. thank you!") 
});
```
