### ISSUE TITLE
JavaScript might not be the best idea because people might use double quotes!!! or you could also just replace the double into single!

### ISSUE THREAD

**Issue by moon05** [jeremywrnr/testing#76]
[issue screenshot](http://codepilot.meteor.com/screenshot/qBZ4kQdtiwEq3pKNt)
[live code here](http://codepilot.meteor.com/render/FhP3eom4pjEjNfk36)
html:
```html
<head>
  <title>my website</title>
</head>

<body>
  <h1>welcome!</h1>
  <p>you can edit this code - please do!</p>
  <h2>here is kitty</h2>
  <img id="kitty" src="http://placekitten.com/202/200"/>
</body>
```
css:
```css
body {
    font-family: Arial, sans-serif;
    padding: 10px;
    margin: 10px;
}

h1 {
    font-size: 3em; 
}

h2 {
    font-size: 1.5em; 
}
```
js:
```js
// rejoice - jquery is enabled!

console.log("Hello world");

$("#kitty").click(function() {
   console.log("you clicked on the kitty. thank you!")
   // more messages below
   console.log("First week of school is crazy man!!!")
});
```
console log:
```
[2:55:51 PM] beginning console output...
[2:55:51 PM] Hello world
```
