### ISSUE TITLE
blah blah lbah

### ISSUE THREAD

**Issue by pgbovine** [jeremywrnr/testing#77]
[issue screenshot](http://codepilot.meteor.com/screenshot/AH26LGGi3S8GWRaaa)
[live code here](http://codepilot.meteor.com/render/BFYrEJ3dTSCk7YBFd)
html:
```html
<head>
  <title>my website</title>
</head>

<body>
  <h1>welcome!</h1>
  <p>you can edit this code - please do!</p>
  <h2>here is kitty</h2>
  <img id="kitty" src="http://placekitten.com/202/200"/>
</body>
```
css:
```css
body {
    font-family: Arial, sans-serif;
    padding: 10px;
    margin: 10px;
}

h1 {
    font-size: 3em; 
}

h2 {
    font-size: 1.5em; 
}
```
js:
```js
// rejoice - jquery is enabled!

console.log("Hello world");

$("#kitty").click(function() {
   console.log("you clicked on the kitty. thank you!") 
});
```
console log:
```
[6:02:14 PM] beginning console output...
[6:02:14 PM] Hello world
[6:02:20 PM] you clicked on the kitty. thank you!
[6:02:20 PM] you clicked on the kitty. thank you!
[6:02:21 PM] you clicked on the kitty. thank you!
[6:02:21 PM] you clicked on the kitty. thank you!
[6:02:21 PM] you clicked on the kitty. thank you!
[6:02:22 PM] you clicked on the kitty. thank you!
```
