### ISSUE TITLE
i dont this like this cats face

### ISSUE THREAD

**Issue by jeremywrnr** [jeremywrnr/testing#80]
[issue screenshot](http://codepilot.meteor.com/screenshot/NRSDkTtvpjdi4bXqb)
[live code here](http://codepilot.meteor.com/render/3vGkqab783jBSRQm7)
html:
```html
<head>
  <title>my website</title>
</head>

<body>
  <h1>welcome!</h1>
  <p>you can edit this code - please do!</p>
  <h2>here is kitty</h2>
  <img id="kitty" src="http://erinhunter.katecary.co.uk/wp-content/uploads/2014/12/science-cat.jpg"/>
</body>
```
css:
```css
body {
    font-family: Arial, sans-serif;
    padding: 10px;
    margin: 10px;
}

h1 {
    font-size: 3em; 
}

h2 {
    font-size: 1.5em; 
}

img {
    width: 100%; 
}
```
js:
```js
// rejoice - jquery is enabled!

console.log("Hello branched world");

$("#kitty").click(function() {
   console.log("Thank you for clicking on the science kitty!") 
});
```
console log:
```
[1:46:46 PM] beginning console output...
[1:46:46 PM] Hello branched world
[1:46:49 PM] Thank you for clicking on the science kitty!
[1:46:50 PM] Thank you for clicking on the science kitty!
[1:46:50 PM] Thank you for clicking on the science kitty!
[1:46:52 PM] Thank you for clicking on the science kitty!
[1:46:52 PM] Thank you for clicking on the science kitty!
```
