### ISSUE TITLE
I can't stop hovering over this kitty.

### ISSUE THREAD

**Issue by aaronzlim** [jeremywrnr/testing#81]
[issue screenshot](http://codepilot.meteor.com/screenshot/5wBy3i7k6GgZCuYjk)
[live code here](http://codepilot.meteor.com/render/8e5MkmMZk2Y5564F9)
html:
```html
<head>
  <title>my website</title>
</head>

<body>
  <h1>welcome!</h1>
  <p>you can edit this code - please do!</p>
  <h2>Here is kitty. Pet the kitty</h2>
  <img id="kitty" src="http://placekitten.com/202/200"/>
  <img id="kitty2" src="http://placekitten.com/g/202/200"/>
</body>

```
css:
```css
body {
    font-family: Arial, sans-serif;
    padding: 10px;
    margin: 10px;
}

h1 {
    font-size: 3em; 
}

h2 {
    font-size: 1.5em; 
}
```
js:
```js
// rejoice - jquery is enabled!

console.log("Hello world");

$("#kitty").click(function() {
   console.log("you clicked on the kitty. thank you!") 
});

$("#kitty2").hover(function() {
   console.log("you hovered over the kitty. Please stop...") 
});
```
console log:
```
[2:26:25 PM EST] beginning console output...
[2:26:25 PM EST] Hello world
```
