### ISSUE TITLE
be more friendly

### ISSUE THREAD

**Issue by jeremywrnr** [jeremywrnr/testing#82]
[issue screenshot](http://codepilot.meteor.com/screenshot/yqcw6GyLJGaoZFear)
[live code here](http://codepilot.meteor.com/render/PymXoTSw7ZjW3S3Wy)
html:
```html
<head>
  <title>my website</title>
</head>

<body>
  <h1>welcome!</h1>
  <p>you can edit this code - please do!</p>
  <h2>Here is kitty. Pet the kitty</h2>
  <img id="kitty" src="http://placekitten.com/202/200"/>
  <img id="kitty2" src="http://placekitten.com/g/202/200"/>
</body>

```
css:
```css
body {
    font-family: Arial, sans-serif;
    padding: 10px;
    margin: 10px;
}

h1 {
    font-size: 3em; 
}

h2 {
    font-size: 1.5em; 
}
```
js:
```js
// rejoice - jquery is enabled!

console.log("Hello world");

$("#kitty").click(function() {
   console.log("you clicked on the kitty. thank you!") 
});

$("#kitty2").hover(function() {
   console.log("you hovered over the kitty. Please stop...") 
});
```
console log:
```
[10:07:16 AM] beginning console output...
[10:07:16 AM] Hello world
```
